apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen
  namespace: default
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen
        - --model_id=Qwen/Qwen3-0.6
        - --backend=huggingface 
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: ""
      resources:
        requests:
          cpu: "4"
          memory: "20Gi"
        limits:
          cpu: "8"
          memory: "110Gi"