# name: Deploy model in AWS EKS
# on:
#   workflow_dispatch:
#   workflow_run:
#     workflows: ["AWS deploy infra"]
#     types:
#       - completed
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# jobs:
  