name: AWS deploy infra

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/aws/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-central-1' }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name qwen-cluster

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          cluster_admin_Danil: ${{secrets.cluster_admin_Danil}}
          cluster_admin_Cejay: ${{secrets.cluster_admin_Cejay}}
          cluster_admin_Nigel: ${{secrets.cluster_admin_Nigel}}
          cluster_admin_Rik: ${{secrets.cluster_admin_Rik}}
          cluster_admin_Andonis: ${{secrets.cluster_admin_Andonis}}